### PR TITLE
Add 'Powered by' to footer bar

### PR DESCRIPTION
**Pull request by neanias**
We needs it

### CODE REVIEW

**Comment by rphi** [comment]
But this isn't minimal mistakes is it?

**Comment by neanias** [comment]
No, but the last one was, see [here](http://comp-soc.com/)

**Comment by rphi** [comment]
I was aware of that (and it seems this design has been quite heavily influenced by it) but also @qaisjp has written it, so although it was historical, it would be more accurate to say Jekyll and Bootstrap. Or potentially use the icons instead of the word marks to save space?

**Comment by neanias** [comment]
Good point, I'll cross out Minimal Mistakes and replace it with Bootstrap!

**Comment by rphi** [comment]
Oh no.... (but also yes) Maybe we could have it randomly choose one of them to have crossed out on each page load?

**Comment by neanias** [comment]
I would also accept that. Now to figure out how to JS...

**Comment by qaisjp** [comment]
what if we included this little nugget of information #29 instead ;)

**Comment by qaisjp** [comment]
I'm not too keen on having this in the footer of every page, though.

**Comment by qaisjp** [comment]
Closing so that we can put the website history being on the websig page.

**Pull request closed without merging**
